LICENSE_DB = {
    "npm": {
        "react": {"license": "MIT", "url": "https://github.com/facebook/react/blob/main/LICENSE"},
        "react-dom": {"license": "MIT", "url": "https://github.com/facebook/react/blob/main/LICENSE"},
        "vue": {"license": "MIT", "url": "https://github.com/vuejs/core/blob/main/LICENSE"},
        "angular": {"license": "MIT", "url": "https://github.com/angular/angular/blob/main/LICENSE"},
        "lodash": {"license": "MIT", "url": "https://github.com/lodash/lodash/blob/master/LICENSE"},
        "express": {"license": "MIT", "url": "https://github.com/expressjs/express/blob/master/LICENSE"},
        "axios": {"license": "MIT", "url": "https://github.com/axios/axios/blob/v1.x/LICENSE"},
        "typescript": {"license": "Apache-2.0", "url": "https://github.com/microsoft/TypeScript/blob/main/LICENSE.txt"},
        "jquery": {"license": "MIT", "url": "https://github.com/jquery/jquery/blob/main/LICENSE.txt"},
        "webpack": {"license": "MIT", "url": "https://github.com/webpack/webpack/blob/main/LICENSE"},
        "babel": {"license": "MIT", "url": "https://github.com/babel/babel/blob/main/LICENSE"},
        "next": {"license": "MIT", "url": "https://github.com/vercel/next.js/blob/canary/license.md"},
        "tailwindcss": {"license": "MIT", "url": "https://github.com/tailwindlabs/tailwindcss/blob/master/LICENSE"},
        "moment": {"license": "MIT", "url": "https://github.com/moment/moment/blob/develop/LICENSE"},
        "redux": {"license": "MIT", "url": "https://github.com/reduxjs/redux/blob/master/LICENSE.md"},
        "rxjs": {"license": "Apache-2.0", "url": "https://github.com/ReactiveX/rxjs/blob/master/LICENSE.txt"},
        "node-sass": {"license": "MIT", "url": "https://github.com/sass/node-sass/blob/master/LICENSE"},
        "jest": {"license": "MIT", "url": "https://github.com/facebook/jest/blob/main/LICENSE"},
        "eslint": {"license": "MIT", "url": "https://github.com/eslint/eslint/blob/main/LICENSE"},
        "prettier": {"license": "MIT", "url": "https://github.com/prettier/prettier/blob/main/LICENSE"},
    },
    "pip": {
        "django": {"license": "BSD-3-Clause", "url": "https://github.com/django/django/blob/main/LICENSE"},
        "flask": {"license": "BSD-3-Clause", "url": "https://github.com/pallets/flask/blob/main/LICENSE.rst"},
        "requests": {"license": "Apache-2.0", "url": "https://github.com/psf/requests/blob/main/LICENSE"},
        "numpy": {"license": "BSD-3-Clause", "url": "https://github.com/numpy/numpy/blob/main/LICENSE.txt"},
        "pandas": {"license": "BSD-3-Clause", "url": "https://github.com/pandas-dev/pandas/blob/main/LICENSE"},
        "scipy": {"license": "BSD-3-Clause", "url": "https://github.com/scipy/scipy/blob/main/LICENSE.txt"},
        "tensorflow": {"license": "Apache-2.0", "url": "https://github.com/tensorflow/tensorflow/blob/master/LICENSE"},
        "pytorch": {"license": "BSD-3-Clause", "url": "https://github.com/pytorch/pytorch/blob/master/LICENSE"},
        "sqlalchemy": {"license": "MIT", "url": "https://github.com/sqlalchemy/sqlalchemy/blob/main/LICENSE"},
        "pytest": {"license": "MIT", "url": "https://github.com/pytest-dev/pytest/blob/main/LICENSE"},
        "celery": {"license": "BSD-3-Clause", "url": "https://github.com/celery/celery/blob/master/LICENSE"},
        "fastapi": {"license": "MIT", "url": "https://github.com/tiangolo/fastapi/blob/master/LICENSE"},
        "pydantic": {"license": "MIT", "url": "https://github.com/pydantic/pydantic/blob/main/LICENSE"},
        "click": {"license": "BSD-3-Clause", "url": "https://github.com/pallets/click/blob/main/LICENSE.rst"},
        "aiohttp": {"license": "Apache-2.0", "url": "https://github.com/aio-libs/aiohttp/blob/master/LICENSE.txt"},
        "beautifulsoup4": {"license": "MIT", "url": "https://www.crummy.com/software/BeautifulSoup/"},
        "lxml": {"license": "BSD-3-Clause", "url": "https://github.com/lxml/lxml/blob/master/LICENSE.txt"},
        "pyyaml": {"license": "MIT", "url": "https://github.com/yaml/pyyaml/blob/master/LICENSE"},
        "toml": {"license": "MIT", "url": "https://github.com/uiri/toml/blob/master/LICENSE"},
    },
    "go": {
        "gin-gonic/gin": {"license": "MIT", "url": "https://github.com/gin-gonic/gin/blob/master/LICENSE"},
        "gorilla/mux": {"license": "BSD-3-Clause", "url": "https://github.com/gorilla/mux/blob/master/LICENSE"},
        "gorm.io/gorm": {"license": "MIT", "url": "https://github.com/go-gorm/gorm/blob/master/LICENSE"},
        "grpc/grpc-go": {"license": "Apache-2.0", "url": "https://github.com/grpc/grpc-go/blob/master/LICENSE"},
        "google.golang.org/protobuf": {"license": "BSD-3-Clause", "url": "https://github.com/golang/protobuf/blob/master/LICENSE"},
        "golang.org/x/crypto": {"license": "BSD-3-Clause", "url": "https://cs.opensource.google/go/x/crypto/+/master:LICENSE"},
        "gopkg.in/yaml.v2": {"license": "Apache-2.0", "url": "https://github.com/go-yaml/yaml/blob/v2/LICENSE"},
        "github.com/stretchr/testify": {"license": "MIT", "url": "https://github.com/stretchr/testify/blob/master/LICENSE"},
        "github.com/spf13/cobra": {"license": "Apache-2.0", "url": "https://github.com/spf13/cobra/blob/master/LICENSE.txt"},
        "github.com/spf13/viper": {"license": "MIT", "url": "https://github.com/spf13/viper/blob/master/LICENSE"},
    },
    "maven": {
        "org.springframework:spring-core": {"license": "Apache-2.0", "url": "https://github.com/spring-projects/spring-framework/blob/main/LICENSE.txt"},
        "org.springframework.boot:spring-boot": {"license": "Apache-2.0", "url": "https://github.com/spring-projects/spring-boot/blob/main/LICENSE.txt"},
        "com.google.guava:guava": {"license": "Apache-2.0", "url": "https://github.com/google/guava/blob/master/COPYING"},
        "junit:junit": {"license": "EPL-1.0", "url": "https://github.com/junit-team/junit4/blob/main/LICENSE-junit.txt"},
        "org.junit.jupiter:junit-jupiter": {"license": "EPL-2.0", "url": "https://github.com/junit-team/junit5/blob/main/LICENSE.md"},
        "com.fasterxml.jackson.core:jackson-databind": {"license": "Apache-2.0", "url": "https://github.com/FasterXML/jackson-databind/blob/2.14/LICENSE"},
        "org.apache.commons:commons-lang3": {"license": "Apache-2.0", "url": "https://github.com/apache/commons-lang/blob/master/LICENSE.txt"},
        "org.projectlombok:lombok": {"license": "MIT", "url": "https://github.com/projectlombok/lombok/blob/master/LICENSE"},
        "org.hibernate:hibernate-core": {"license": "LGPL-2.1", "url": "https://github.com/hibernate/hibernate-orm/blob/main/license.txt"},
        "org.mockito:mockito-core": {"license": "MIT", "url": "https://github.com/mockito/mockito/blob/main/LICENSE"},
    },
    "rust": {
        "serde": {"license": "MIT OR Apache-2.0", "url": "https://github.com/serde-rs/serde/blob/master/LICENSE-MIT"},
        "serde_json": {"license": "MIT OR Apache-2.0", "url": "https://github.com/serde-rs/json/blob/master/LICENSE-MIT"},
        "tokio": {"license": "MIT", "url": "https://github.com/tokio-rs/tokio/blob/master/LICENSE"},
        "rand": {"license": "MIT OR Apache-2.0", "url": "https://github.com/rust-random/rand/blob/master/LICENSE-MIT"},
        "clap": {"license": "MIT OR Apache-2.0", "url": "https://github.com/clap-rs/clap/blob/master/LICENSE-MIT"},
        "reqwest": {"license": "MIT OR Apache-2.0", "url": "https://github.com/seanmonstar/reqwest/blob/master/LICENSE-MIT"},
        "actix-web": {"license": "MIT OR Apache-2.0", "url": "https://github.com/actix/actix-web/blob/master/LICENSE-MIT"},
        "axum": {"license": "MIT", "url": "https://github.com/tokio-rs/axum/blob/main/LICENSE"},
        "diesel": {"license": "MIT OR Apache-2.0", "url": "https://github.com/diesel-rs/diesel/blob/master/LICENSE-MIT"},
        "chrono": {"license": "MIT OR Apache-2.0", "url": "https://github.com/chronotope/chrono/blob/main/LICENSE-MIT"},
    },
}
