import dayjs from 'dayjs';
import type { User, Book, BorrowRecord, Reservation, Fine, Message } from '@/types';

const generateId = () => Math.random().toString(36).substring(2, 11);

const bookCovers = [
  'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=book%20cover%20literary%20novel%20elegant%20design&image_size=square',
  'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=history%20book%20cover%20classic%20style&image_size=square',
  'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=science%20fiction%20book%20cover%20futuristic&image_size=square',
  'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=philosophy%20book%20cover%20minimalist&image_size=square',
  'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=computer%20science%20book%20cover%20tech&image_size=square',
];

export const mockUsers: User[] = [
  {
    id: 'user_student_001',
    username: 'student001',
    name: '张三',
    role: 'student',
    department: '计算机科学与技术学院',
    createdAt: dayjs().subtract(1, 'year').format('YYYY-MM-DD'),
  },
  {
    id: 'user_student_002',
    username: 'student002',
    name: '李四',
    role: 'student',
    department: '经济管理学院',
    createdAt: dayjs().subtract(8, 'month').format('YYYY-MM-DD'),
  },
  {
    id: 'user_teacher_001',
    username: 'teacher001',
    name: '王教授',
    role: 'teacher',
    department: '文学院',
    createdAt: dayjs().subtract(3, 'year').format('YYYY-MM-DD'),
  },
  {
    id: 'user_teacher_002',
    username: 'teacher002',
    name: '刘老师',
    role: 'teacher',
    department: '历史学院',
    createdAt: dayjs().subtract(2, 'year').format('YYYY-MM-DD'),
  },
  {
    id: 'user_admin_001',
    username: 'admin',
    name: '图书馆管理员',
    role: 'admin',
    department: '图书馆',
    createdAt: dayjs().subtract(5, 'year').format('YYYY-MM-DD'),
  },
];

export const mockBooks: Book[] = [
  {
    id: 'book_001',
    isbn: '9787020002207',
    title: '红楼梦',
    author: '曹雪芹',
    publisher: '人民文学出版社',
    publishDate: '2008-07-01',
    category: '文学小说',
    location: 'A区-中文图书',
    totalCopies: 5,
    availableCopies: 3,
    cover: bookCovers[0],
    description: '《红楼梦》是中国古代四大名著之首，以贾宝玉、林黛玉、薛宝钗的爱情婚姻悲剧为主线，展现了封建社会的全景图。',
    price: 59.8,
    borrowCount: 156,
    createdAt: dayjs().subtract(2, 'year').format('YYYY-MM-DD'),
  },
  {
    id: 'book_002',
    isbn: '9787101003048',
    title: '史记',
    author: '司马迁',
    publisher: '中华书局',
    publishDate: '2013-09-01',
    category: '历史传记',
    location: 'A区-中文图书',
    totalCopies: 3,
    availableCopies: 1,
    cover: bookCovers[1],
    description: '《史记》是西汉史学家司马迁撰写的纪传体史书，是中国历史上第一部纪传体通史，被列为"二十四史"之首。',
    price: 128.0,
    borrowCount: 89,
    createdAt: dayjs().subtract(2, 'year').format('YYYY-MM-DD'),
  },
  {
    id: 'book_003',
    isbn: '9787111213826',
    title: '深入理解计算机系统',
    author: 'Randal E.Bryant',
    publisher: '机械工业出版社',
    publishDate: '2016-11-01',
    category: '计算机科学',
    location: 'B区-外文图书',
    totalCopies: 8,
    availableCopies: 5,
    cover: bookCovers[4],
    description: '本书从程序员的视角详细阐述计算机系统的本质概念，帮助程序员理解程序在计算机上执行的底层原理。',
    price: 139.0,
    borrowCount: 234,
    createdAt: dayjs().subtract(1, 'year').format('YYYY-MM-DD'),
  },
  {
    id: 'book_004',
    isbn: '9787100014472',
    title: '西方哲学史',
    author: '罗素',
    publisher: '商务印书馆',
    publishDate: '2011-06-01',
    category: '哲学宗教',
    location: 'A区-中文图书',
    totalCopies: 4,
    availableCopies: 2,
    cover: bookCovers[3],
    description: '罗素的《西方哲学史》是一部经典的哲学史著作，以清晰流畅的文笔讲述了从古希腊到现代的西方哲学发展历程。',
    price: 88.0,
    borrowCount: 112,
    createdAt: dayjs().subtract(3, 'year').format('YYYY-MM-DD'),
  },
  {
    id: 'book_005',
    isbn: '9787532731504',
    title: '三体',
    author: '刘慈欣',
    publisher: '重庆出版社',
    publishDate: '2008-01-01',
    category: '文学小说',
    location: 'A区-中文图书',
    totalCopies: 10,
    availableCopies: 4,
    cover: bookCovers[2],
    description: '《三体》是刘慈欣创作的系列长篇科幻小说，由《三体》《三体Ⅱ·黑暗森林》《三体Ⅲ·死神永生》组成。',
    price: 93.0,
    borrowCount: 312,
    createdAt: dayjs().subtract(1, 'year').format('YYYY-MM-DD'),
  },
  {
    id: 'book_006',
    isbn: '9787300136776',
    title: '经济学原理',
    author: '曼昆',
    publisher: '中国人民大学出版社',
    publishDate: '2015-05-01',
    category: '经济管理',
    location: 'A区-中文图书',
    totalCopies: 6,
    availableCopies: 3,
    cover: bookCovers[0],
    description: '《经济学原理》是目前国内市场上最受欢迎的经济学入门教材，以其通俗易懂的语言和生动的案例著称。',
    price: 128.0,
    borrowCount: 178,
    createdAt: dayjs().subtract(2, 'year').format('YYYY-MM-DD'),
  },
  {
    id: 'book_007',
    isbn: '9787115358426',
    title: '算法导论',
    author: 'Thomas H.Cormen',
    publisher: '人民邮电出版社',
    publishDate: '2013-01-01',
    category: '计算机科学',
    location: 'B区-外文图书',
    totalCopies: 5,
    availableCopies: 2,
    cover: bookCovers[4],
    description: '《算法导论》全面覆盖了算法理论的方方面面，是计算机科学领域的经典教材。',
    price: 128.0,
    borrowCount: 198,
    createdAt: dayjs().subtract(2, 'year').format('YYYY-MM-DD'),
  },
  {
    id: 'book_008',
    isbn: '9787544722908',
    title: '百年孤独',
    author: '加西亚·马尔克斯',
    publisher: '南海出版公司',
    publishDate: '2011-06-01',
    category: '文学小说',
    location: 'A区-中文图书',
    totalCopies: 4,
    availableCopies: 0,
    cover: bookCovers[0],
    description: '《百年孤独》是魔幻现实主义文学的代表作，描写了布恩迪亚家族七代人的传奇故事。',
    price: 55.0,
    borrowCount: 267,
    createdAt: dayjs().subtract(3, 'year').format('YYYY-MM-DD'),
  },
];

export const mockBorrowRecords: BorrowRecord[] = [
  {
    id: 'borrow_001',
    userId: 'user_student_001',
    bookId: 'book_001',
    book: mockBooks[0],
    user: mockUsers[0],
    borrowDate: dayjs().subtract(25, 'day').format('YYYY-MM-DD'),
    dueDate: dayjs().subtract(25, 'day').add(30, 'day').format('YYYY-MM-DD'),
    renewed: false,
    status: 'borrowed',
    createdAt: dayjs().subtract(25, 'day').format('YYYY-MM-DD'),
  },
  {
    id: 'borrow_002',
    userId: 'user_student_001',
    bookId: 'book_005',
    book: mockBooks[4],
    user: mockUsers[0],
    borrowDate: dayjs().subtract(10, 'day').format('YYYY-MM-DD'),
    dueDate: dayjs().subtract(10, 'day').add(30, 'day').format('YYYY-MM-DD'),
    renewed: false,
    status: 'borrowed',
    createdAt: dayjs().subtract(10, 'day').format('YYYY-MM-DD'),
  },
  {
    id: 'borrow_003',
    userId: 'user_teacher_001',
    bookId: 'book_002',
    book: mockBooks[1],
    user: mockUsers[2],
    borrowDate: dayjs().subtract(40, 'day').format('YYYY-MM-DD'),
    dueDate: dayjs().subtract(40, 'day').add(60, 'day').format('YYYY-MM-DD'),
    renewed: false,
    status: 'borrowed',
    createdAt: dayjs().subtract(40, 'day').format('YYYY-MM-DD'),
  },
  {
    id: 'borrow_004',
    userId: 'user_student_002',
    bookId: 'book_006',
    book: mockBooks[5],
    user: mockUsers[1],
    borrowDate: dayjs().subtract(50, 'day').format('YYYY-MM-DD'),
    dueDate: dayjs().subtract(50, 'day').add(30, 'day').format('YYYY-MM-DD'),
    renewed: false,
    status: 'overdue',
    createdAt: dayjs().subtract(50, 'day').format('YYYY-MM-DD'),
  },
  {
    id: 'borrow_005',
    userId: 'user_student_001',
    bookId: 'book_003',
    book: mockBooks[2],
    user: mockUsers[0],
    borrowDate: dayjs().subtract(60, 'day').format('YYYY-MM-DD'),
    dueDate: dayjs().subtract(60, 'day').add(30, 'day').format('YYYY-MM-DD'),
    returnDate: dayjs().subtract(35, 'day').format('YYYY-MM-DD'),
    renewed: true,
    status: 'returned',
    createdAt: dayjs().subtract(60, 'day').format('YYYY-MM-DD'),
  },
];

export const mockReservations: Reservation[] = [
  {
    id: 'reserve_001',
    userId: 'user_student_002',
    bookId: 'book_008',
    book: mockBooks[7],
    user: mockUsers[1],
    reserveDate: dayjs().subtract(2, 'day').format('YYYY-MM-DD HH:mm:ss'),
    expireDate: dayjs().subtract(2, 'day').add(24, 'hour').format('YYYY-MM-DD HH:mm:ss'),
    status: 'pending',
    createdAt: dayjs().subtract(2, 'day').format('YYYY-MM-DD HH:mm:ss'),
  },
];

export const mockFines: Fine[] = [
  {
    id: 'fine_001',
    userId: 'user_student_002',
    borrowRecordId: 'borrow_004',
    bookTitle: '经济学原理',
    user: mockUsers[1],
    type: 'overdue',
    amount: 10.0,
    reason: '逾期20天',
    status: 'unpaid',
    createdAt: dayjs().subtract(20, 'day').format('YYYY-MM-DD'),
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg_001',
    userId: 'user_student_001',
    title: '借阅成功提醒',
    content: '您已成功借阅《红楼梦》，请于到期日前归还。',
    type: 'borrow',
    read: true,
    createdAt: dayjs().subtract(25, 'day').format('YYYY-MM-DD HH:mm:ss'),
  },
  {
    id: 'msg_002',
    userId: 'user_student_001',
    title: '还书提醒',
    content: '您借阅的《红楼梦》将在5天后到期，请及时归还或办理续借。',
    type: 'reminder',
    read: false,
    createdAt: dayjs().subtract(1, 'day').format('YYYY-MM-DD HH:mm:ss'),
  },
  {
    id: 'msg_003',
    userId: 'user_student_002',
    title: '逾期提醒',
    content: '您借阅的《经济学原理》已逾期20天，请尽快归还并缴纳罚款。',
    type: 'reminder',
    read: false,
    createdAt: dayjs().subtract(20, 'day').format('YYYY-MM-DD HH:mm:ss'),
  },
];

export const generateMockBorrowRecords = (books: Book[], users: User[]): BorrowRecord[] => {
  const records: BorrowRecord[] = [];
  for (let i = 0; i < 50; i++) {
    const book = books[Math.floor(Math.random() * books.length)];
    const user = users.filter(u => u.role !== 'admin')[Math.floor(Math.random() * (users.length - 1))];
    const borrowDaysAgo = Math.floor(Math.random() * 90);
    const borrowDuration = user.role === 'teacher' ? 60 : 30;
    
    records.push({
      id: generateId(),
      userId: user.id,
      bookId: book.id,
      book: book,
      user: user,
      borrowDate: dayjs().subtract(borrowDaysAgo, 'day').format('YYYY-MM-DD'),
      dueDate: dayjs().subtract(borrowDaysAgo, 'day').add(borrowDuration, 'day').format('YYYY-MM-DD'),
      renewed: Math.random() > 0.7,
      status: borrowDaysAgo > borrowDuration ? 'overdue' : 'borrowed',
      createdAt: dayjs().subtract(borrowDaysAgo, 'day').format('YYYY-MM-DD'),
    });
  }
  return records;
};
